sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VerE8H772Tjn3DwQ7u3IrN5gwOxJ1MB5W5ASa52dZ8Ng+H/l0MKwm8bPwjDkCbi1ftbk4T66YeY763JqCxDoGCPIvh8+dpyjTykcAgjMEc6MVRC25p0HiT39r1DTlOSDNIcd11OEYEjcSCIBSvCLjIV3CjDGVAKBxQHERFGEXOqcizsnMO90XoG6XLNZl8w3n4R73o7AirBlkpC97EUL33adXGD0i0l/NRgJJeG/npeT4USiWKe5SAElzShGP6+BVQLtM2gDtnSlzxIPpy7ggr0gkXxpZ2FYLigStDcJ+MJ1LDIzPIETamf8r0zlZbXDGitZb/F1h0a2ZRi7hEi8lEzzzQ2cTWJgc34UYldxdd7B8KmPA4LQ4mxLFXo+qBrAdW/5gzJAW9OU4kqE3+s+Ys0raNPwL/aJJQoDy/ZbLGScBHUpM4ZLvt1EiFzvQyBJ1FbcRhJKVu9sMqeTF8QF/y1D174Z9ljoFAg1pAx4lGhhdj5POsX6du1g/Qg8BWbwNt5hdgByMpvIkpi5LE44EmIDYUAdn0ezD9FnoDOh6ObkN8xKRClnIBSvgstGnvTR21ArmmZ7B1fFIq+V2+jEV2YxamqEAgayjdhlcngWd2/vfd7BgbBrUzngHzVFaqgvrlxwRi3LSkxPrBhH8uM/qIwREuOk1NkKnO4geXMfcMs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Isaac-Bickerstaff-Physician-and-Astrologer_2644
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy